title: Helloooooo-world
author: Developer Lv1.
email: lucyya99@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
url : https://lucyya99.github.io
baseurl: /

# 
# 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: texture/posts/:title/
texture:
  title: 개발공부일지. Developer Study Log
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true
  
  navigation:
    - title: Log
      url: "/log/"
    - title: Resume
      url: "/resume"
  
  

  # generate social links in footer
  social_links:
    twitter: lucyya99
    github:  lucyya99
    linkedIn: lucyya99
    rss: rss

  
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed